### PR TITLE
Module 6

### LINKED ISSUE #45: Module 6: In Case of a Collision
Your task is to make Module 6. https://www.figma.com/design/sMtRqfPSadb6TeFRmF7D0n/UCSD-Health-Design-Files?node-id=5917-21017&t=M4MHE6Uo8tu0yngt-1

For this task you need to:
1. Create a new Module 6 component that uses the snap screen components
2. Make the In Case of a Collision page
3. Make the Bicycle Safety Facts page
4. Make the Crash Protocol slideshow 
5. Implement the ready to take the module quiz page

You don't have to do the Module 6 quiz just the snap screens. Please let me know if you have any questions!

### PR DESCRIPTION
**Pull request by aaronchan32**
## Tracking Info

Resolves #45

## Changes

- Added all sections in module
- Added animations for Crash Protocol section
- Updated ModuleButtons component so that it is horizontally fixed

## Testing

http://localhost:3000/module6/

## Confirmation of Change

image

### CODE REVIEW

**Comment by km322** [comment]
Hey Aaron amazing job!

A couple of comments I have:
- Can you wrap the sidebar in a div like we did for module 1  so it stays the same size for every module
```
<div className={styles.hideModile}>
        <Sidebar />
</div>
```
and...
```
@media (max-width: 768px) {
  .sidebar {
    display: none;
  }
}
```
- Another thing is that the bottom buttons have a little bit of different behaviors when zooming in and out. It looks like it goes to the bottom of the page but I thought it should stay underneath the content like in the previous page. This is probably a small thing you can ignore if you disagree.  

https://github.com/user-attachments/assets/28be2076-f537-48f4-81a2-af4859a5b522

Also Quick Questions:
- are the progress bar and next and back buttons supposed to get smaller as you zoom out?
- One thing I notices is that when I spam click the next button, the animation skips. Is this fine?

https://github.com/user-attachments/assets/009092b0-89fd-4ce8-9b9a-98ae8c4ee5ad

Amazing job!

**Comment by km322** [comment]
Hey Aaron! Perfect, everything looks amazing!

the main point of the div is to fix this issue where the sidebar is cut off as shown below. I think wrapping it in a div will fix this but if you have an alternative solution that would be amazing!

https://github.com/user-attachments/assets/1c82fe3a-7a9b-4cc8-ad3d-71747e22ed5d

Thanks!

**Review by OrigamiStarz — COMMENTED** [review]
Hey Aaron, nice work, especially with the animation! Everything looks good to me.

I did notice a few minor things:
1. The progress bar at the top does not always fill in correctly. With my Google Chrome profile, it seems like the more I zoom out, the less aligned the "filled in" part is (see video below). I think this is somewhat related to how I have a default large font size in my Chrome settings, as I tested this out on a normal profile and found that it required more zoom to see a difference. However, I feel like most users will not encounter this issue (and even if they do, it does not affect the content), so it might not be worth fixing in the first place. 

https://github.com/user-attachments/assets/793c716e-73a0-4dd8-b2df-d054095fb980

2. Something that struck out to me while reviewing module 6 is how the hyperlink is black, as opposed to the light blue used in module 7. I was thinking it might be worth asking the designers to confirm that they are supposed to be different, as opposed to a universal hyperlink color. 

Screenshot 2025-05-20 at 6 03 38 PM

Screenshot 2025-05-20 at 6 04 17 PM

I'll approve this after you fix the sidebar as Ketan mentioned. Great work!

**Comment by aaronchan32** [comment]
Thanks for the feedback! I fixed the `Sidebar` component and also fixed the bug with the progress bar. I also decided to completely redo the implementation for the progress bar so there should no longer be a flicker after the initial re-render.

I reached out to Justin about the hyperlink inconsistency and will get back to you when he responds.

File: frontend/src/app/module6/page.tsx [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import ModuleIntro from "../components/AllModules/ModuleIntro/ModuleIntro";
+import ModuleSliderContainer from "../components/ModuleSliderContainer/ModuleSliderContainer";
+import Sidebar from "../components/Sidebar/Sidebar";
+import { TitleScreen } from "../components/quiz_components/TitleScreen";
+
+import styles from "./Module6.module.css";
+import BicycleSafetyFacts from "./components/BicycleSafetyFacts/BicycleSafetyFacts";
+import CrashProtocol from "./components/CrashProtocol/CrashProtocol";
+
+export default function Module2() {
```
Comment (km322) [inline frontend/src/app/module6/page.tsx:14]: can you rename the module to module6

**Comment by aaronchan32** [comment]
> Hey Aaron, when testing the code out in Safari I face loads of issues when using svgs, is it possible to make it work in safari or other browsers better?
> 
>  Screen.Recording.2025-05-21.at.1.23.22.PM.mov 
> This also occurs in the home page for safari:
> 
>  Screen.Recording.2025-05-21.at.1.25.59.PM.mov

Hey Ketan, thanks for bringing this up. I unfortunately use a Windows laptop, so it's a bit difficult for me to debug on Safari at the moment. However, once I get my GitHub student re-verification approved I will have access to Safari emulation software that will make this process easier. I will update you once I get this all fixed!

**Review by eshaan-s18 — DISMISSED** [review]
Fantastic job Aaron! This looks amazing! I approve this PR. Also there are a couple of merge conflicts, if you could resolve those that would be awesome and super helpful! Thanks for all your hard work on this!!

**Review by km322 — APPROVED** [review]
Great job!

**Review by OrigamiStarz — DISMISSED** [review]
Hey Aaron, everything looks good to me! Just one very minor thing I noticed: 
The text isn't vertically centered well, so when I use a font size of large/very large through chrome settings, it looks off-centered (see below). 
Screenshot 2025-05-30 at 3 39 59 PM

However, I think this won't affect most people, so I'll approve it. Great work!
